version: '3.8'

services:
  auth-server:
    build: ./auth-server
    ports:
      - "8081:8081"

  client-api:
    build: ./client-api
    ports:
      - "8082:8080"
    depends_on:
      - auth-server

  gateway:
    build: ./gateway
    ports:
      - "8080:8080"
    depends_on:
      - client-api

  client-ui:
    build: ./client-ui
    ports:
      - "3000:80"
    depends_on:
      - gateway 