server:
  port: 9001
logging:
  level:
    root: info

spring:
  data:
    mongodb:
      database: bot
      username: root
      password: example
  web:
    resources:
      chain:
        cache: false
