server:
  port: 9002
logging:
  level:
    root: info

spring:
  data:
    mongodb:
      database: bot
      username: root
      password: example
  rsocket:
    server:
      mapping-path: /rsocket
      transport: websocket
  web:
    resources:
      chain:
        cache: false
