server:
  port: 9000
logging:
  level:
    root: info

spring:
  application:
    id: ""
    name: client_api${spring.application.id}
  data:
    mongodb:
      database: bot
      username: root
      password: example
  web:
    resources:
      chain:
        cache: false
