server:
  port: 9000
logging:
  level:
    root: info

spring:
  mongodb:
    uri: ${SPRING_MONGODB_URI:mongodb://root:example@localhost:27017/bot?authSource=admin}
  rsocket:
    server:
      mapping-path: /rsocket
      transport: websocket
  web:
    resources:
      chain:
        cache: false
