server:
  port: 9002
logging:
  level:
    root: info

spring:
  application:
    id: ""
    name: client_api${spring.application.id}
  data:
    mongodb:
      database: bot
      username: root
      password: example
  web:
    resources:
      chain:
        cache: false

rsocket:
  host: localhost
  port: 9091
  rpath: /rsocket
  type: client_api
  path: bot.api
