server:
  port: 9003
logging:
  level:
    root: info

spring:
  application:
    id: ""
    name: bot_api${spring.application.id}
  data:
    mongodb:
      database: bot
      username: root
      password: example
  rsocket:
    server:
      mapping-path: /rsocket
      transport: websocket
  web:
    resources:
      chain:
        cache: false
  cloud:
    consul:
      discovery:
        instance-group: bot_api
        service-name: bot_api
        instance-id: bot_${spring.application.id}
bot:
  api:
    telegram:
      host: https://api.telegram.org
      timeout: 500
    instagram:
      host: https://graph.facebook.com/v9.0/
      timeout: 500

