server:
  port: 9003
logging:
  level:
    root: info

io.rsocket.broker.client:
  route-id: 00000000-0000-0000-0000-000000000002
  service-name: bot-api
  tags:
    INSTANCE_NAME: bot-api
  brokers:
    - tcp://localhost:8002

spring:
  data:
    mongodb:
      database: bot
      username: root
      password: example
  rsocket:
    server:
      mapping-path: /rsocket
      transport: tcp
  web:
    resources:
      chain:
        cache: false

bot:
  api:
    telegram:
      host: https://api.telegram.org
      timeout: 500
    instagram:
      host: https://graph.facebook.com/v9.0/
      timeout: 500
